### ISSUE TITLE
Allow passing a Timeout value to HTTP methods (to override object's default timeout)

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/JKI-HTTP-REST-Client#11]
It's possible to set the timeout for HTTP transactions, using "Write Timeout.vi" accessor method.

![http get rest with timeout](https://user-images.githubusercontent.com/381432/52813159-06bad280-304e-11e9-8a84-d9d870875ee3.png)

That VI is in the Accessors sub-palette.

![image](https://user-images.githubusercontent.com/381432/52813272-441f6000-304e-11e9-8da7-c1cbe2d36507.png)

However, this isn't obvious for users ([see here](https://github.com/JKISoftware/JKI-REST-Client/issues/10)) and they might want to have different timeouts for specific transactions. So, it would be helpful to have a Timeout argument on each HTTP method that would override the default value.

![image](https://user-images.githubusercontent.com/381432/52879206-6af39a00-3113-11e9-963a-2a0cb6b06cbc.png)

![image](https://user-images.githubusercontent.com/381432/52879210-6e872100-3113-11e9-836d-95e4096d2cdf.png)

A timeout of "0" as the signal to use the object's value could be good (as opposed to "-1" which typically means "No Timeout") since a timeout value of "0" isn't really useful for anything practical (any HTTP transaction will take a time > 0).

**Comment by jimkring** [comment]
@francois-normandin @tmaila @JKISoftware/jki-staff any thoughts?

**Comment by francois-normandin** [comment]
The current method is analogous to an Instrument communication protocol. (e.g. VISA Serial). The proposed one is matching the native HTTP API.  This is really a matter of preference. 
However, since the REST API and the HTTP API are more likely to be used in the same OOP hierarchy, I would favour the change to have matching functionality.
Your proposed implementation is backwards compatible, so I don't see any worries about breaking existing code either.

**Comment by carlodri** [comment]
@jimkring looks _very_ good to me! Thanks!

**Comment by jimkring** [comment]
Implemented in [1.3.2](https://github.com/JKISoftware/JKI-HTTP-REST-Client/releases/tag/1.3.2) and available for [download with VIPM](https://resources.jki.net/http-rest-client-for-labview).
